[phases.setup]
nixPkgs = ["python311", "curl", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "curl -LsSf https://astral.sh/uv/install.sh | sh"
]

[phases.build]
cmds = []

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

