[phases.setup]
nixPkgs = ["python311", "curl", "pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "curl -LsSf https://astral.sh/uv/install.sh | sh",
  "export PATH=\"$HOME/.cargo/bin:$PATH\""
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

